name: Daily Holiday Tweets

on:
  schedule:
    - cron: "0 7 * * *"  # Her gün 07:00 UTC (Türkiye saatiyle 10:00)
  workflow_dispatch:      # Elle tetiklemek için

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Tweepy yükle
        run: pip install tweepy

      - name: Tatilleri tweetle
        run: python tweet.py
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
